-- USERS TABLE
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(20) NOT NULL,
  "full_name" varchar(255),
  "company_name" varchar(255),
  "is_active" boolean DEFAULT true,
  "is_approved" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- CATEGORIES TABLE
CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "parent_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- PRODUCTS TABLE
CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" int NOT NULL,
  "category_id" int,
  "name" varchar(255) NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- PRODUCT_UNITS TABLE
CREATE TABLE "product_units" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "pack_size" int NOT NULL,
  "price" numeric(12,2) NOT NULL,
  "stock" int DEFAULT 0,
  "min_order_quantity" int DEFAULT 1,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- PRODUCT_IMAGES TABLE
CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "url" varchar(1024) NOT NULL,
  "alt_text" varchar(255),
  "sort_order" int DEFAULT 0,
  "updated_at" timestamp
);

-- CARTS TABLE
CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyer_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- CART_ITEMS TABLE
CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int NOT NULL,
  "product_unit_id" int NOT NULL,
  "quantity" int NOT NULL DEFAULT 1,
  "added_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- ORDERS TABLE
CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyer_id" int NOT NULL,
  "total_amount" numeric(12,2),
  "status" varchar(50) NOT NULL DEFAULT 'pending',
  "shipping_address_id" int,
  "billing_address_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- ORDER_ITEMS TABLE
CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "product_unit_id" int NOT NULL,
  "quantity" int NOT NULL,
  "unit_price" numeric(12,2) NOT NULL,
  "total_price" numeric(12,2),
  "updated_at" timestamp
);

-- ADDRESSES TABLE
CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "line1" varchar(255) NOT NULL,
  "line2" varchar(255),
  "city" varchar(100),
  "state" varchar(100),
  "postal_code" varchar(50),
  "country" varchar(100),
  "phone" varchar(50),
  "updated_at" timestamp
);

-- PAYMENTS TABLE
CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "amount" numeric(12,2),
  "method" varchar(50),
  "status" varchar(50),
  "transaction_ref" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

-- FOREIGN KEYS WITH CASCADE
ALTER TABLE "products" 
  ADD FOREIGN KEY ("seller_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "products" 
  ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "product_units" 
  ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_images" 
  ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "carts" 
  ADD FOREIGN KEY ("buyer_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "cart_items" 
  ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "cart_items" 
  ADD FOREIGN KEY ("product_unit_id") REFERENCES "product_units" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "orders" 
  ADD FOREIGN KEY ("buyer_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "orders" 
  ADD FOREIGN KEY ("shipping_address_id") REFERENCES "addresses" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "orders" 
  ADD FOREIGN KEY ("billing_address_id") REFERENCES "addresses" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "order_items" 
  ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "order_items" 
  ADD FOREIGN KEY ("product_unit_id") REFERENCES "product_units" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "addresses" 
  ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "payments" 
  ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE CASCADE;